export enum ProductActionType {

   
    ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST",
    ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS",              // Done
    ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL",

    PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST",    
    PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS",        // Done
    PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL",

    UPLOAD_PICTURE_REQUEST = "UPLOAD_PICTURE_REQUEST",
    UPLOAD_PICTURE_SUCCESS = "UPLOAD_PICTURE_SUCCESS",          // Done
    UPLOAD_PICTURE_FAIL = "UPLOAD_PICTURE_FAIL",
    UPLOAD_PICTURE_RESET = "UPLOAD_PICTURE_RESET",

    NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST",
    NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS",                // Done
    NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL",
    NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET",

    DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS',      // Done
    DELETE_PRODUCT_RESET = 'DELETE_PRODUCT_RESET',
    DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL',

    UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST',
    UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS',      // Done
    UPDATE_PRODUCT_RESET = 'UPDATE_PRODUCT_RESET',
    UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL',

    CLEAR_ERRORS = "CLEAR_ERRORS"
}